### ISSUE TITLE
How to convert mp4s to a dataset for "Initialize the first frame model"?

### ISSUE THREAD

**Issue by soskek** [AlgoHunt/StreamRF#5]
Thank you for releasing the code.

I'm trying to follow README. But, I failed to train a model at the step of "Initialize the first frame model."

```
python opt.py -t logs dataset/MeetRoom/discussion -c configs/meetroom_init.json --scale 1.0

Detected LLFF dataset
Traceback (most recent call last):
  File "opt.py", line 271, in <module>
    dset = datasets[args.dataset_type](
  File "/StreamRF/util/dataset.py", line 13, in auto_dataset
    return LLFFDataset(root, *args, **kwargs)
  File "/StreamRF/util/llff_dataset.py", line 69, in __init__
    self.sfm = SfMData(
  File "/StreamRF/util/llff_dataset.py", line 244, in __init__
    raise Exception("Unknow dataset type")
Exception: Unknow dataset type
```

In `llff_dataset.py`, `readLLFF` is searching for images (`dataset/MeetRoom/discussion/images`) but didn't find them because the dataset contains mp4s and poses only.

```
tree dataset/MeetRoom
dataset/MeetRoom
├── discussion
│   ├── cam_0.mp4
│   ├── cam_1.mp4
│   ├── cam_10.mp4
│   ├── cam_11.mp4
│   ├── cam_12.mp4
│   ├── cam_2.mp4
│   ├── cam_3.mp4
│   ├── cam_4.mp4
│   ├── cam_5.mp4
│   ├── cam_6.mp4
│   ├── cam_7.mp4
│   ├── cam_8.mp4
│   ├── cam_9.mp4
│   └── poses_bounds.npy
...
```

I guess that you use some kind of script to make the `images` directory from the original dataset.
Could you upload it?

**Comment by soskek** [comment]
maybe the same issue with #4

**Comment by Spark001** [comment]
Please check the latest commit, I update a script to prepare dataset.

**Comment by soskek** [comment]
thank you!
